unique_ids:
  forms: {}
  modules: {augment: 4HZ3FHYVJLUH5OK52VXFOBOCROJE44ZX}
  server_modules: {}
  assets: {standard-page.html: 55XWR5S3TFG63TJQSNIUIIO25MVM3QFZ, theme.css: NJV7ZAA724QJ3JK42KEIRR3KTOHLA5WS}
